Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,6 +22,7 @@ jobs:
           ECS_IP: ${{ secrets.ECS_IP }}
         run: |
           sshpass -p ${{ secrets.ECS_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }} "
+          set -x  # 开启调试
           cd /usr
           git clone https://github.com/ZPolister/SCAU-OS-Design.git
           cd SCAU-OS-Design/os_djg
@@ -29,5 +30,11 @@ jobs:
           conda activate os-env            # 激活 os-env 环境
           git pull --force
           git checkout master
-          python manage.py runserver 0.0.0.0:8000
+          if pgrep -f 'manage.py runserver'; then
+            PID=\$(pgrep -f 'manage.py runserver')
+            kill \$PID && echo 'Old process killed' || echo 'Failed to kill the process'
+          else
+            echo 'No process found to kill'
+          fi
+          nohup python manage.py runserver 0.0.0.0:8000 &
           "
